import Head from 'next/head';
import Link from 'next/link';
import {useEffect, useState} from 'react';
import {CharactersCard} from '../components';
import styles from '../styles/Home.module.css';
import Image from "next/image";
import mainLogo from "../public/main_logo.svg";

export default function Home() {
    const [data, setData] = useState([]);
    const [info, setInfo] = useState();
    const [page, setPage] = useState(1);
    const [searchValue, setSearchValue] = useState('');

    useEffect(() => {
        fetch(`https://rickandmortyapi.com/api/character/?page=${page}`)
            .then((res) => res.json())
            .then((res) => {
                setData((prev) => [...prev, ...res.results]);
                setInfo(res.info);
            });
    }, [page]);

    useEffect(() => {
        fetch(`https://rickandmortyapi.com/api/character/?name=${searchValue}`)
            .then((res) => res.json())
            .then((res) => {
                if (res.error) {
                    setData([]);
                    setInfo(undefined);
                    return;
                }
                setData(res.results);
                setInfo(res.info);
            });
    }, [searchValue]);

    return (
        <>
            <Head>
                <title>Rick & Morty | Characters</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <div style={{
                paddingTop: 20,
                display: 'flex',
                justifyContent: 'center'
            }}>
                <Image src={mainLogo} alt={''} width={450}/>
            </div>

            <input className={styles.searchInput}
                   value={searchValue}
                   onChange={(e) => setSearchValue(e.target.value)}
                   placeholder={'Search by name...'}
            />

            <div style={{height: '100px'}}/>

            <main className={styles.grid}>
                {data.map((character) => (
                    <Link href={`/characters/${character.id}`} key={character.id}>
                        <CharactersCard
                            name={character.name}
                            species={character.species}
                            image={character.image}
                        />
                    </Link>
                ))}
            </main>
            <div
                style={{
                    display: 'grid',
                    justifyContent: 'center',
                    alignItems: 'center',
                    height: '100px'
                }}
            >
                {info?.next && (
                    <button
                        className={styles.loadMoreButton}
                        onClick={() => setPage((prev) => ++prev)}
                    >
                        <span>LOAD MORE</span>
                    </button>
                )}
            </div>
        </>
    );
}