import Head from "next/head";
import {useEffect, useState} from "react";
import {LocationsContext} from "../store";
import {instance} from "../utlis";
import {LoadMoreButton, LocationsList} from "../components";
import styles from "../styles/Home.module.css";
import Image from "next/image";
import portal from "../public/portal.svg";

export default function Locations() {
    const [state, setState] = useState([]);
    const [searchValue, setSearchValue] = useState('');
    const [info, setInfo] = useState();
    const [page, setPage] = useState(1);

    useEffect(() => {
        instance({
            url: "location",
            params: {
                page,
            },
        }).then((res) => {
            setState(res.data.results);
            setInfo(res.data.info);
        });
    }, [page]);

    useEffect(() => {
        fetch(`https://rickandmortyapi.com/api/location/?name=${searchValue}`)
            .then((res) => res.json())
            .then((res) => {
                if (res.error) {
                    setState([]);
                    setInfo(undefined);
                    return;
                }
                setState(res.results);
                setInfo(res.info);
            });
    }, [searchValue]);

    return (
        <LocationsContext.Provider value={{
            locations: state,
            info,
            setPage: setPage,
        }}>
            <Head>
                <title>Rick & Morty | Locations</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <div style={{
                paddingTop: 20,
                display: 'flex',
                justifyContent: 'center'
            }}>
                <Image src={portal} alt={''} width={300}/>
            </div>

            <input className={styles.searchInput}
                   value={searchValue}
                   onChange={(e) => setSearchValue(e.target.value)}
                   placeholder={'Search by location...'}
            />

            <div style={{height: '100px'}}/>

            <main>
                <LocationsList/>
                <div
                    style={{
                        display: 'grid',
                        justifyContent: 'center',
                        alignItems: 'center',
                        height: '100px'
                    }}
                >
                    <LoadMoreButton/>
                </div>
                <br></br>
            </main>
        </LocationsContext.Provider>
    );
}
