import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import {useRouter} from 'next/router';
import {useEffect, useState} from 'react';
import {CharactersCard} from '../../components';
import styles from '../../styles/Home.module.css';

export default function CharacterProfile() {
    const router = useRouter();
    const [data, setData] = useState({});
    const [characters, setCharacters] = useState([]);

    useEffect(() => {
        router.query.pid &&
        fetch(`https://rickandmortyapi.com/api/episode/${router.query.pid}`)
            .then((res) => res.json())
            .then((data) => {
                console.log(data);
                setData(data);
            });
    }, [router.query]);

    useEffect(() => {
        if (data !== {}) {
            data.characters?.map((character) => {
                const characterId = character.split('/character/')[1];

                fetch(`https://rickandmortyapi.com/api/character/${characterId}`)
                    .then((res) => res.json())
                    .then((data) => {
                        setCharacters((prev) => [...prev, data]);
                    });
            });
        }
    }, [data]);

    return (
        <>
            <Head>
                <title>{data.name}</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main>
                <h1 className={styles.episodeName}>{data.name}</h1>
                <div className={styles.grid2}>
                    <div>
                        <span className={styles.episodeId}>Episode</span>
                        <span className={styles.episodeId}>{data.episode}</span>
                    </div>
                    <div>
                        <span className={styles.episodeId}>Air Date</span>
                        <span className={styles.episodeId}>
                            {new Date(data.air_date).toLocaleDateString('en-US', {
                                month: 'long',
                                day: 'numeric',
                                year: 'numeric',
                            })}
                        </span>
                    </div>
                </div>

                <div className={styles.grid}>
                    <h3>Cast</h3>
                    {characters?.map((character, index) => {
                        return (
                            <Link href={`/characters/${character.id}`} key={index}>
                                <CharactersCard
                                    name={character.name}
                                    species={character.species}
                                    image={character.image}
                                />
                            </Link>
                        );
                    })}
                </div>
            </main>
        </>
    );
}
