import Head from 'next/head';
import EpisodeCard from '../../components/episode-card';
import {useEffect, useState} from 'react';
import Link from 'next/link';
import styles from '../../styles/Home.module.css';
import {LoadMoreButton} from "../../components";
import Image from "next/image";
import watching from "../../public/watching.svg";

export default function Episodes() {
    const [page, setPage] = useState(1);
    const [info, setInfo] = useState();
    const [episodes, setEpisodes] = useState([]);
    const [searchValue, setSearchValue] = useState('');

    useEffect(() => {
        fetch(`https://rickandmortyapi.com/api/episode?page=${page}`)
            .then((response) => response.json())
            .then((data) => {
                console.log(data.results);
                setEpisodes((prev) => [...prev, ...data.results]);
                setInfo(data.info);
            });
    }, [page]);

    useEffect(() => {
        fetch(`https://rickandmortyapi.com/api/episode?name=${searchValue.toString()}`)
            .then((response) => response.json())
            .then((data) => {
                if (data.error) {
                    setEpisodes([]);
                    setInfo(undefined);
                    return;
                }
                console.log(data.results);
                setEpisodes(data.results);
                setInfo(data.info);
            });
    }, [searchValue]);

    return (
        <>
            <Head>
                <title>Rick & Morty | Episodes</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <div style={{
                paddingTop: 20,
                display: 'flex',
                justifyContent: 'center'
            }}>
                <Image src={watching} alt={''} height={190}/>
            </div>

            <main
                style={{
                    backgroundColor: 'white',
                    display: 'flex',
                    flexDirection: 'column',
                    alignItems: 'center',
                }}
            >
                <div style={{height: '100px'}}/>

                <input className={styles.searchInput}
                       value={searchValue}
                       onChange={(e) => setSearchValue(e.target.value)}
                       placeholder={'Filter by name or episode (ex. S01 or S01E02)'}
                />

                <div className={styles.grid}>
                    {episodes.map((episode, index) => (
                        <Link href={`/episodes/${episode.id}`} key={index}>
                            <EpisodeCard
                                air_date={episode.air_date}
                                name={episode.name}
                                episode={episode.episode}
                            />
                        </Link>
                    ))}
                </div>
            </main>
            <div
                style={{
                    display: 'grid',
                    justifyContent: 'center',
                    alignItems: 'center',
                    height: '100px'
            }}
            >
                {info?.next && (
                    <button
                        className={styles.loadMoreButton}
                        onClick={() => setPage((prev) => ++prev)}
                    >
                        <span>LOAD MORE</span>
                    </button>
                )}
            </div>
        </>
    );
}
